testando cobertura menor que 80%

diff --git a/.github/workflows/ci-cd-pipeline.yaml b/.github/workflows/ci-cd-pipeline.yaml
--- a/.github/workflows/ci-cd-pipeline.yaml
+++ b/.github/workflows/ci-cd-pipeline.yaml
@@ -32,41 +32,13 @@ jobs:
       with:
         token: ${{ secrets.CODECOV_TOKEN }}
     
-    # - name: Check Jest Unit Test Coverage
-    #   id: coverage
-    #   run: |
-    #     # Recupera o arquivo de cobertura JSON gerado pelo Jest
-    #     COVERAGE_FILE="coverage/coverage-final.json"
-        
-    #     # Inicializa variáveis para armazenar os totais de linhas e cobertas
-    #     total_lines=0
-    #     total_covered=0
-    
-    #     # Itera sobre cada arquivo no JSON de cobertura e soma as linhas e cobertas
-    #     for file in $(cat $COVERAGE_FILE | jq -r 'keys[]'); do
-    #       # Conta o total de linhas e as cobertas para cada arquivo
-    #       file_total_lines=$(cat $COVERAGE_FILE | jq ".\"$file\".s | values | add")
-    #       file_covered_lines=$(cat $COVERAGE_FILE | jq ".\"$file\".s | values | map(select(. > 0)) | length")
-          
-    #       # Acumula os totais de linhas e cobertas
-    #       total_lines=$((total_lines + file_total_lines))
-    #       total_covered=$((total_covered + file_covered_lines))
-    #     done
-    
-    #     # Calcula a cobertura em percentual
-    #     if [ $total_lines -eq 0 ]; then
-    #       COVERAGE=100
-    #     else
-    #       COVERAGE=$(echo "scale=2; ($total_covered / $total_lines) * 100" | bc)
-    #     fi
-    
-    #     echo "Coverage: $COVERAGE%"
-    
-    #     # Verifica se a cobertura é menor que 80% e falha no pipeline caso seja
-    #     if [ $(echo "$COVERAGE < 80" | bc) -eq 1 ]; then
-    #       echo "Coverage deve ser maior ou igual a 80%"
-    #       exit 1
-    #     fi
+    - name: Check Codecov status
+      run: |
+        curl -s https://codecov.io/api/gh/${{ github.repository }}/reports/latest | jq '.coverage'
+        if [ $(curl -s https://codecov.io/api/gh/${{ github.repository }}/reports/latest | jq '.coverage') -lt 80 ]; then
+          echo "Coverage is below 80%. Failing the pipeline."
+          exit 1
+        fi
     
     - name: Run Integration Tests
       run: npm run test:e2e
